### ISSUE TITLE
Deep Neural Network doesn't work properly

### ISSUE THREAD

**Issue by Mamatu** [Mamatu/oap#82]
Neural network implementation for weights in hidden layer, returns different values than calculated in page: https://www.nnwj.de/backpropagation.html

**Comment by marcinmatula** [comment]
Fixed in implementation from July and August 2019

**Comment by marcinmatula** [comment]
Current master has correct behaviour
commit 8211025cbd14cd5c1748af1839d7da8b4c6d6e96
